create table app_users (
    id bigint generated by default as identity primary key,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    email varchar(320) not null unique,
    password_hash varchar(255) not null,
    phone_number varchar(40),
    role varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp,
    version bigint
);

create table pets (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    species varchar(60) not null,
    breed varchar(80),
    age integer,
    owner_id bigint not null,
    version bigint,
    constraint fk_pets_owner foreign key (owner_id) references app_users (id)
);

create table sitting_requests (
    id bigint generated by default as identity primary key,
    pet_id bigint not null,
    requester_id bigint not null,
    sitter_id bigint,
    start_time timestamp not null,
    end_time timestamp not null,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp,
    version bigint,
    constraint fk_sitting_requests_pet foreign key (pet_id) references pets (id),
    constraint fk_sitting_requests_requester foreign key (requester_id) references app_users (id),
    constraint fk_sitting_requests_sitter foreign key (sitter_id) references app_users (id),
    constraint ck_sitting_requests_time_range check (end_time > start_time)
);

create index idx_pets_owner_id on pets (owner_id);
create index idx_sitting_requests_requester_id on sitting_requests (requester_id);
create index idx_sitting_requests_sitter_id on sitting_requests (sitter_id);
create index idx_sitting_requests_status_start_time on sitting_requests (status, start_time);
