spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/pawsitters}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:pawsitters}
spring.datasource.password=${DATABASE_PASSWORD:pawsitters_dev_password}

spring.jpa.properties.hibernate.format_sql=true
